/**
* marr.example1.kotlin
* The backend module RESTful built with spring boot kotlin and springdoc-openapi
*
* OpenAPI spec version: 0.0.1-SNAPSHOT
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

/**
 *  * @param apiKey */
data class AccessApiKeyResponse (        val apiKey: kotlin.String
) {
}
